### PR TITLE
Create package.json

### LINKED ISSUE #7: Add package.json for Yarn support
Trying to install from Yarn produces the following error:

```
yarn install v0.22.0
info No lockfile found.
[1/4] Resolving packages...
error Couldn't find manifest in "https://github.com/vedmack/angular-colorpicker.git".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

This means it's missing a `package.json` file. Many people are migrating away from Bower nowadays, so adding support for that is a good idea.

### PR DESCRIPTION
**Pull request by brunofin**
Adds a `package.json` file.

I cannot register it as an npm module as I am not the author.

Closes #7

### CODE REVIEW

**Comment by vedmack** [comment]
Thanks will register it now

**Comment by vedmack** [comment]
will try to publish today...

**Comment by vedmack** [comment]
done,

https://www.npmjs.com/package/angular-colorpicker-dr

npm i angular-colorpicker-dr

**Comment by brunofin** [comment]
@vedmack awesome, thanks!

**Pull request merged**
